.gitignore
Dockerfile
README.md
docker-compose.example.yml

maybe better preference to use Docker:
* `COPY` project files directly from local instead of git-cloned
* add `CMD` into `Dockerfile`, so we don't need run command `mango` in the cotainer after running mango instance
* add `docker-compose.example.yml` as example configuration
* add `docker-compose.yml` into `.gitignore`

better Docker configuration

---

.gitignore
README.md
docker-compose.yml
env.example

This is generally cleaner and ensures that the `docker-compose.yml` can be a part of the source repository (which allows for updating it).
For future reference, it's possible to use any variable in the `.env` file (which follows the syntax of `VARNAME=value`) in `docker-compose.yml` by using `${VARNAME}`.
--
This does break existing configurations and pulls, if you merge this users _will_ have to create a `.env` file. I also added some comments as to what each variable does/stands for.

Use a .env file for docker-compose configuration.

---

Dockerfile.arm64v8

Hello, 
Thank you very much for your work, and for supporting ARM architectures.
There was a small issue when I was building the arm64v8 image. 
Specifically: `/usr/lib/arm-linux-gnueabihf/libgc.so` is not part of the arm64 `libgc-dev` package, it's actual position is `/usr/lib/aarch64-linux-gnu/libgc.so`
Reffering to:
[Debian Package Repo FileList](https://debian.pkgs.org/9/debian-main-arm64/libgc-dev_7.4.2-8_arm64.deb.html)
[Ubuntu Package Repo FileList](https://packages.ubuntu.com/focal/arm64/libgc-dev/filelist)
This pull request fixes the error.
--
Commit Message:
The Repo Maintainer was using the location of libgc.so from the armhf package, however, according to:
https://debian.pkgs.org/9/debian-main-arm64/libgc-dev_7.4.2-8_arm64.deb.html and …

[arm64] Fix Wrong libgc.so location when building Image

---

spec/util_spec.cr
src/library/title.cr
src/util/signature.cr
src/util/util.cr

I realized that I had several files which of filename is ended with '.CBZ', and they are not scanned by Mango.
(they are generated by accident, when moving Linux files whose name contains forbidden characters in Windows via Samba haha...)
I resolved this problem by adding `is_interesting_file` method.

Make file extension check case-insensitive

---

.github/workflows/build.yml
README.md
shard.yml
src/mango.cr
src/views/reader.html.ecr

In [v0.19.0](https://github.com/hkalexling/Mango/releases/tag/v0.19.0) we switched from raw CSS to Less, but that accidentically introduced a bug where the background color on the reader page becomes white instead of black. It's now fixed in this PR.

Fix incorrect background color on reader page

---

src/util/util.cr

Fix #158 
The server returns HTTP 500 error when requested '/favion.ico'
The handler worked fine, but send_file has failed with the error `Missing MIME type for extension ".ico"`
so I register mime type for .ico file

Fix HTTP 500 Error when accessing the favicon

---

Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8

This PR moves the mango binary from `/` to `/usr/local/bin`.
I did this because:
I tried to run the official docker image with `docker run --user myuser`, but this caused mango to think that `$HOME` for that user was `/`. Mango expects the `MAIN_DIRECTORY_PATH` at `$HOME/mango` but `/mango`  now clashes with the binary location.

Move binary in docker image to /usr/local

---

src/routes/api.cr

Use [`ETag`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) header for HTTP caching
* thumbnails and pages
* hashing image data with SHA1 (strong validation)
* Resolve #213 
* dimensions
* It took so long times for big manga files, since it requires to read an entire zip file. For the device that has a bad I/O performance, It would be helped.
* I use a zip_path of an entry and its mtime for hashing (SHA1), set ETag for weak validation

HTTP cache for thumbnails, pages, dimensions

---

public/js/reader.js
src/views/reader.html.ecr

This resolve #196
Preload lookahead: 3 pages
Started from p32, it preloaded next 3 pages (pp.33-35)
After reading p33 and p34, it preloaded p36, p37 each.
Fix #217
Fix #218
This resolve one of suggestion from #147 
---
A below picture shows a modal menu when the mode is paged mode.
It has the checkbox for toggling flip animation and the range input to set preload pages
I'm curious that its layout looks good (especially about a position of the checkbox... 😜)

Enhance the paged mode reader

---

src/config.cr
src/library/cache.cr
src/library/entry.cr
src/library/library.cr
src/library/title.cr
src/library/types.cr
src/mango.cr
src/routes/main.cr
src/util/web.cr

To improve page loading, I cached lots of data. The principles are:
* Avoid accessing `info.json` files
* Reuse results of method that called many times with same arguments
Like `entry_display_name`, cached `entry_cover_url` would improve rendering `src/views/components/card.html.ecr`. This is very effective.
This would avoid to access `info.json`
It's okay that sort options are saved when accessing library, book with parameters. I removed unnecessary actions. This would avoid to access `info.json`
This utility implemented at `cache.cr` helps cached data to be preserved after scanning.
This caches:
* `cover_url` of each entry
* results of `deep_read_page_count` of each title
* sort options from `info.json` files
I think the second one is quite effective.
There are lots of calls …

Improve loading pages (library, titles)

---

spec/util_spec.cr
src/plugin/downloader.cr
src/util/util.cr

Fixes #212.
This PR adds a new utility function `sanitize_filename` as follows
https://github.com/hkalexling/Mango/blob/ccf558eaa7657a96ebe7277828ad7fdf6397fc9a/src/util/util.cr#L124-L141
Unit tests included:
https://github.com/hkalexling/Mango/blob/ccf558eaa7657a96ebe7277828ad7fdf6397fc9a/spec/util_spec.cr#L65-L73

Stricter sanitization rules for download filenames

---

src/library/entry.cr
src/library/library.cr
src/library/title.cr
src/routes/api.cr

This PR updates the following API endpoints:
- `/api/library`:
- adds the `shallow` parameter to return only the top-level titles, without their nested titles and entries
- `/api/book/:title_id`
- adds the `shallow` parameter to return only the title information, without its entries and nested titles
- adds the `sort` and `ascend` parameters to control the sorting method and direction of entries

API Improvements

---

src/config.cr
src/library/entry.cr
src/library/library.cr
src/library/title.cr
src/library/types.cr
src/mango.cr
src/storage.cr
src/util/signature.cr

I just added `YAML::Serializable` to `Entry`, `Title` and `Library`. I ignored some cache field. A filename of saved instance is `library.yml.zip`. In there, `instance.yml` is. My library (12,000 entries, about 500GB) makes 1.5MB zip file for this (8MB unzipped). It saves an instance file after every scanning. It loads instance file on boot and examine loaded titles via scanning.
After loading library instance, there are scanned titles. We should remove removed, renamed file, reuse remains and scan new.
* check existence at titles, remove removed ones
* make content-changed titles stable
* skip making a new instance of a title that already exists
See `Library#scan` and `Title#examine`.
The `signature` is good for identifying files even renamed, moved but finding re-scan targets does need …

Reuse scanned titles on boot and scanning

---

src/library/title.cr

It's unnecessary to call `sorted_entries` in `load_progress_for_all_entries` at `deep_read_page_count`, because we use its aggregated sum. It would make an initial page loading fast.
I didn't test yet in a large library, but it will be builded soon
---
I tested it. it seems ok!

Avoid a unnecessary sorting

---

src/library/library.cr
src/library/title.cr
src/routes/api.cr

This is a follow-up PR on #231. We replace the `shallow` parameter with `depth` for fine control.

Use `depth` instead of `shallow` in API

---

src/library/library.cr
src/library/title.cr
src/routes/admin.cr

Resolve #257
Mango think some titles removed but they are actually not. They are found in other directory.
Since they are checked as 'deleted', Mango removed them from `title_hash` after scan job over and mark them unavailable.
After make new titles or entries, cancel the reserved jobs for them if there are.

Fix bug on scanning

---

migration/sort_title.12.cr
public/js/title.js
src/library/cache.cr
src/library/entry.cr
src/library/library.cr
src/library/title.cr
src/routes/api.cr
src/routes/main.cr
src/storage.cr
src/util/util.cr
src/views/components/card.html.ecr
src/views/library.html.ecr
src/views/title.html.ecr

Resolve #182 
* add column `sort_title` on `ids` and `titles` tables (migration file no.12)
* implement `/api/admin/sort_title/:title_id`
* `name` is an optional query parameter and if empty, make `sort_title` `null`
* add the name(title) option to sort titles
* use `sort_title` instead `title` for sorting titles and entries in auto and title options
* sort titles too
* cache sorted titles
* make helper methods to remove sorted caches
* add a `Sort Title` field below the `Display Name` field in edit modal
* set a placeholder with `file title` (same with `title` mentioned in https://github.com/hkalexling/Mango/issues/182#issuecomment-1000752956) at the `Display Name` field and the `Sort Title` field
* restore a display name with the file title when a user submits an empty input
* remove …

Implement custom sort title and sorting titles

---

shard.lock
shard.yml
src/routes/admin.cr

Sanitize parameters on user edit page (fixes #289)

---

spec/config_spec.cr
src/config.cr
src/util/util.cr

I'm not sure if you're interested in this, but it made running Mango much easier on my local install.
This allows the default config to source values from ENV variables if they are set. With this change we don't have to modify the docker CMD or edit the config.yml and then relaunch.

Allow config defaults to be sourced from ENV

---

src/util/signature.cr

Fixed a reported issue at [here](https://github.com/hkalexling/Mango/issues/215#issuecomment-1157632921)

Fix Dir.contents_signature to detect valid image files

---

public/js/reader.js
src/views/reader.html.ecr

Adding the image fit feature mentioned in #147.
The setFit function is hardcoded to look for the css file and attribute on those exact spots and looks likely to break if that file is changed. Asides from this, the only other way I know is to make a function to look for it given the name of the file and attribute, but it'd be a function that would only be used on this one occasion.
And if anyone has a better idea for how the option should appear in the settings I'd like to hear it, design is not my passion.

Fit image options

---

.ameba.yml
spec/asset/plugins/plugin/info.json
spec/plugin_spec.cr
spec/spec_helper.cr
src/plugin/plugin.cr

Fixes #320 and adds unit tests for the helper functions

Use html parser in plugin helper functions

---

public/js/plugin-download.js
src/logger.cr
src/plugin/plugin.cr
src/routes/api.cr
src/views/plugin-download.html.ecr

1. Hide the "Subscribe" button if a plugin is not "subscribable". A plugin is only subscribable if it's targets at least API v2, and implements the `newChapters` function.
2. Clear the page when switching plugins.

Hide subscribe btn

---

src/util/util.cr

Loading `manifest.json` would result in an Error 404, which prevented Mango from being added to the homescreen as a fullscreen web app. Fixed that by adding `/manifest.json` to the static files.

Fix for Error 404 on manifest.json
